const state={session:null,user:null,docs:[]};
document.addEventListener("DOMContentLoaded",()=>{bind();restore()});
const $=id=>document.getElementById(id);
function bind(){
 $("loginForm").addEventListener("submit",login);$("logoutBtn").onclick=logout;$("refreshBtn").onclick=dashboard;
 $("changePasswordBtn").onclick=()=>$("passwordModal").classList.remove("hidden");$("cancelPasswordBtn").onclick=()=>$("passwordModal").classList.add("hidden");
 $("changePasswordForm").addEventListener("submit",changePassword);$("documentSearch").oninput=debounce(loadDocs,300);
 $("statusFilter").onchange=loadDocs;$("typeFilter").onchange=loadDocs;$("newIncomingBtn").onclick=openIncoming;$("opinionForm").addEventListener("submit",saveOpinion);$("cancelOpinionBtn").onclick=closeOpinion;
 $("cancelIncomingBtn").onclick=closeIncoming;$("incomingForm").addEventListener("submit",saveIncoming);
 $("closeDocumentBtn").onclick=()=>$("documentModal").classList.add("hidden");
}
function restore(){try{let s=JSON.parse(localStorage.getItem(APP_CONFIG.SESSION_KEY)||"null");if(!s?.token)return showLogin();state.session=s;state.user=s.user;showApp();dashboard()}catch(e){showLogin()}}
let apiBusy=0;
function loading(title="กำลังดำเนินการ...",text="กรุณารอสักครู่"){
  apiBusy++;
  if(apiBusy===1 && window.Swal){
    Swal.fire({title,text,allowOutsideClick:false,allowEscapeKey:false,showConfirmButton:false,didOpen:()=>Swal.showLoading()});
  }
}
function loadingClose(){
  apiBusy=Math.max(0,apiBusy-1);
  if(apiBusy===0 && window.Swal && Swal.isVisible()) Swal.close();
}
async function api(action,p={},auth=true){let b={action,...p};if(auth&&state.session?.token)b.token=state.session.token;loading("กำลังเชื่อมต่อระบบ...","ระบบกำลังดำเนินการ กรุณารอสักครู่");try{let r=await fetch(APP_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify(b)}),t=await r.text(),j;try{j=JSON.parse(t)}catch(e){throw Error("API ส่งข้อมูลกลับมาไม่ใช่ JSON")}if(!j.ok){if(j.error==="SESSION_EXPIRED")forceLogout();throw Error(j.error||"เกิดข้อผิดพลาด")}return j}finally{loadingClose()}}
async function login(e){e.preventDefault();$("loginBtn").disabled=true;try{let r=await api("login",{username:$("username").value.trim(),password:$("password").value},false);state.session={token:r.data.token,user:r.data.user};state.user=r.data.user;localStorage.setItem(APP_CONFIG.SESSION_KEY,JSON.stringify(state.session));showApp();toast("เข้าสู่ระบบสำเร็จ","success");dashboard()}catch(e){toast(e.message,"error")}finally{$("loginBtn").disabled=false}}
async function logout(){try{await api("logout")}catch(e){}forceLogout("ออกจากระบบแล้ว")}
function forceLogout(m=""){localStorage.removeItem(APP_CONFIG.SESSION_KEY);state.session=null;state.user=null;showLogin();if(m)toast(m)}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userName").textContent=state.user?.FullName||"-";$("userPosition").textContent=state.user?.Position||"-";$("userRoles").textContent=(state.user?.Roles||[]).join(" · ");let ok=(state.user?.Roles||[]).some(r=>["ADMIN","REGISTRAR"].includes(r));$("newIncomingBtn").classList.toggle("hidden",!ok);$("assistantPanel").classList.toggle("hidden",!(state.user?.Roles||[]).includes("ASSISTANT_SSO"))}
async function dashboard(){try{let r=await api("getDashboard");let d=r.data||{},c=d.counts||{};$("totalDocs").textContent=d.total||0;$("countAssistant").textContent=c.WAIT_ASSISTANT_OPINION||0;$("countSSO").textContent=c.WAIT_SSO||0;$("countAck").textContent=c.WAIT_ACKNOWLEDGEMENT||0;$("countProgress").textContent=c.IN_PROGRESS||0;$("countCompleted").textContent=c.COMPLETED||0;await loadDocs();if((state.user?.Roles||[]).includes("ASSISTANT_SSO")) await loadAssistantQueue()}catch(e){toast(e.message,"error")}}
async function loadAssistantQueue(){try{let r=await api("getDocuments",{status:"WAIT_ASSISTANT_OPINION",documentType:"INCOMING"});let docs=r.data||[];$("assistantRows").innerHTML=docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||"-")}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(d.ReceiveDate||"-")}</td><td class="px-4 py-3 text-right"><button class="px-3 py-1.5 rounded-lg bg-slate-800 text-white" onclick="openOpinion('${jse(d.DocumentID)}')">ให้ความเห็น</button></td></tr>`).join("");$("assistantEmpty").classList.toggle("hidden",!!docs.length);$("assistantCount").textContent=docs.length}catch(e){toast(e.message,"error")}}
async function openOpinion(id){try{let r=await api("getDocument",{documentId:id}),d=r.data||{},x=d.document||{};$("opinionDocumentId").value=x.DocumentID||id;$("opinionRegisterNo").textContent=x.RegisterNo||"-";$("opinionSubject").textContent=x.Subject||"-";$("opinionSender").textContent=x.SenderOrganization||x.SenderName||"-";$("suggestedUser").innerHTML='<option value="">-- เลือกผู้รับผิดชอบ --</option>';let users=(await api("getAssignableUsers")).data||[];users.forEach(u=>{let o=document.createElement("option");o.value=u.UserID;o.textContent=`${u.FullName} — ${u.Position||""}`;$("suggestedUser").appendChild(o)});$("opinionText").value="";$("opinionModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function closeOpinion(){$("opinionModal").classList.add("hidden")}
async function saveOpinion(e){e.preventDefault();let id=$("opinionDocumentId").value,suggested=$("suggestedUser").value;if(!suggested)return toast("กรุณาเลือกผู้รับผิดชอบที่เสนอ","error");let b=$("saveOpinionBtn");b.disabled=true;try{await api("submitOpinion",{documentId:id,data:{OpinionType:"RECOMMEND_ASSIGN",SuggestedUserID:suggested,OpinionText:$("opinionText").value.trim()}});closeOpinion();toast("บันทึกความเห็นและส่งต่อให้ สสอ. แล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function loadDocs(){try{let r=await api("getDocuments",{q:$("documentSearch").value.trim(),status:$("statusFilter").value,documentType:$("typeFilter").value});state.docs=r.data||[];renderDocs()}catch(e){toast(e.message,"error")}}
function renderDocs(){$("documentRows").innerHTML=state.docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||d.DocumentNo||"-")}</td><td class="px-4 py-3">${esc(type(d.DocumentType))}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(d.ReceiveDate||d.BookDate||"-")}</td><td class="px-4 py-3">${badge(d.CurrentStatus)}</td><td class="px-4 py-3 text-right"><button class="text-blue-700" onclick="openDoc('${jse(d.DocumentID)}')">ดูรายละเอียด</button></td></tr>`).join("");$("emptyDocuments").classList.toggle("hidden",!!state.docs.length)}
async function openDoc(id){try{let r=await api("getDocument",{documentId:id}),d=r.data||{},x=d.document||{};$("modalTitle").textContent=x.Subject||"รายละเอียดเอกสาร";$("documentDetail").innerHTML=`<div class="grid md:grid-cols-2 gap-4">${item("ประเภท",type(x.DocumentType))}${item("เลขทะเบียน/เลขที่",x.RegisterNo||x.DocumentNo||"-")}${item("วันที่รับ",x.ReceiveDate||"-")}${item("เวลา",x.ReceiveTime||"-")}${item("ผู้ส่ง",x.SenderName||"-")}${item("หน่วยงาน",x.SenderOrganization||"-")}${item("เรื่อง",x.Subject||"-")}${item("สถานะ",status(x.CurrentStatus))}</div>`;$("fileList").innerHTML=(d.files||[]).map(f=>`<div class="border rounded-xl p-3 flex justify-between"><span>${esc(f.FileName)}</span><a target="_blank" class="text-blue-700" href="https://drive.google.com/file/d/${encodeURIComponent(f.DriveFileID)}/view">เปิดไฟล์</a></div>`).join("")||"ยังไม่มีไฟล์";$("workflowTimeline").innerHTML=(d.workflow||[]).map(w=>`<div class="border-l-2 pl-4 pb-4"><b>${esc(w.ActionCode)}</b><div class="text-xs text-slate-500">${esc(w.ActionDateTime||"")}</div><div>${esc(w.Detail||"")}</div></div>`).join("")||"ยังไม่มีประวัติ";$("documentModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function openIncoming(){$("incomingModal").classList.remove("hidden");let n=new Date();$("receiveDate").value=n.toISOString().slice(0,10);$("receiveTime").value=n.toTimeString().slice(0,5)}
function closeIncoming(){$("incomingModal").classList.add("hidden");$("incomingForm").reset()}
async function saveIncoming(e){e.preventDefault();let f=$("mainPdf").files[0];if(!f)return toast("กรุณาเลือก PDF","error");if(f.type!=="application/pdf")return toast("รองรับเฉพาะ PDF","error");if(f.size>10*1024*1024)return toast("ไฟล์เกิน 10 MB","error");let b=$("saveIncomingBtn");b.disabled=true;try{let p={DocumentType:"INCOMING",BookNo:$("bookNo").value.trim(),BookDate:$("bookDate").value,ReceiveDate:$("receiveDate").value,ReceiveTime:$("receiveTime").value,SenderName:$("senderName").value.trim(),SenderOrganization:$("senderOrganization").value.trim(),Subject:$("subject").value.trim(),RelatedOrgUnitID:$("relatedOrgUnitID").value.trim(),RelatedJobID:$("relatedJobID").value.trim(),UrgencyLevel:$("urgencyLevel").value,DueDate:$("dueDate").value};let r=await api("createDocument",{data:p});const documentId=r?.data?.DocumentID,registerNo=r?.data?.RegisterNo;if(!documentId)throw Error("API ไม่ได้ส่ง DocumentID กลับมา");let raw=await b64(f);if(!raw)throw Error("อ่านข้อมูล PDF ไม่สำเร็จ");await api("uploadFile",{documentId:documentId,fileName:f.name,mimeType:"application/pdf",base64:raw,fileRole:"MAIN_DOCUMENT"});closeIncoming();toast("บันทึกหนังสือรับสำเร็จ เลขรับ "+(r.data.RegisterNo||"-"),"success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
function b64(f){return new Promise((res,rej)=>{let x=new FileReader();x.onload=()=>res(String(x.result).split(",")[1]);x.onerror=rej;x.readAsDataURL(f)})}
async function changePassword(e){e.preventDefault();let n=$("newPassword").value;if(n.length<6)return toast("รหัสผ่านใหม่ต้องมีอย่างน้อย 6 ตัวอักษร","error");if(n!==$("confirmPassword").value)return toast("ยืนยันรหัสผ่านไม่ตรงกัน","error");try{await api("changePassword",{oldPassword:$("oldPassword").value,newPassword:n});$("passwordModal").classList.add("hidden");$("changePasswordForm").reset();toast("เปลี่ยนรหัสผ่านสำเร็จ","success")}catch(e){toast(e.message,"error")}}
function type(x){return({INCOMING:"หนังสือรับ",OUTGOING:"หนังสือส่งออก",CIRCULAR:"หนังสือเวียน",ORDER:"คำสั่ง"})[x]||x||"-"}
function status(x){return({WAIT_ASSISTANT_OPINION:"รอความเห็น ผช.สสอ.",WAIT_SSO:"รอ สสอ. พิจารณา",WAIT_ACKNOWLEDGEMENT:"รอรับทราบ",IN_PROGRESS:"กำลังดำเนินการ",COMPLETED:"เสร็จสิ้น",CANCELLED:"ยกเลิก"})[x]||x||"-"}
function badge(x){return`<span class="inline-flex px-2.5 py-1 rounded-full text-xs bg-slate-100">${esc(status(x))}</span>`}
function item(a,b){return`<div><div class="text-xs text-slate-500">${esc(a)}</div><div class="font-medium">${esc(b)}</div></div>`}
function toast(m,t="info"){
  if(window.Swal){
    Swal.fire({toast:true,position:"bottom-end",icon:t==="error"?"error":t==="success"?"success":t==="warning"?"warning":"info",title:String(m),showConfirmButton:false,timer:3500,timerProgressBar:true});
  }else{
    const x=$("toast"); x.textContent=String(m); x.classList.remove("hidden"); clearTimeout(window.tt); window.tt=setTimeout(()=>x.classList.add("hidden"),3500);
  }
}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function jse(v){return String(v??"").replace(/\\/g,"\\\\").replace(/'/g,"\\'")}function debounce(f,d){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>f(...a),d)}}window.openDoc=openDoc;
