const state={session:null,user:null,docs:[],currentDocument:null,currentTask:null};
document.addEventListener("DOMContentLoaded",()=>{bind();restore()});
const $=id=>document.getElementById(id);let apiBusy=0;
function roles(){return state.user?.Roles||[]} function hasRole(r){return roles().includes(r)} function isAnyRole(a){return a.some(r=>roles().includes(r))}
function bind(){
 $("loginForm").addEventListener("submit",login);$("logoutBtn").onclick=logout;$("refreshBtn").onclick=dashboard;$("changePasswordBtn").onclick=()=>$("passwordModal").classList.remove("hidden");$("cancelPasswordBtn").onclick=()=>$("passwordModal").classList.add("hidden");$("changePasswordForm").addEventListener("submit",changePassword);
 $("documentSearch").oninput=debounce(loadDocs,300);$("statusFilter").onchange=loadDocs;$("typeFilter").onchange=loadDocs;$("newIncomingBtn").onclick=openIncoming;$("cancelIncomingBtn").onclick=closeIncoming;$("incomingForm").addEventListener("submit",saveIncoming);
 $("opinionForm").addEventListener("submit",saveOpinion);$("cancelOpinionBtn").onclick=closeOpinion;$("assignForm").addEventListener("submit",saveAssignment);$("cancelAssignBtn").onclick=closeAssign;
 $("cancelTaskBtn").onclick=closeTask;$("ackTaskBtn").onclick=acknowledgeTask;$("progressTaskBtn").onclick=updateTaskProgress;$("completeTaskBtn").onclick=completeTask;$("closeDocumentBtn").onclick=()=>$("documentModal").classList.add("hidden");
}
function restore(){try{const s=JSON.parse(localStorage.getItem(APP_CONFIG.SESSION_KEY)||"null");if(!s?.token)return showLogin();state.session=s;state.user=s.user;showApp();dashboard()}catch(e){showLogin()}}
function loading(title="กำลังดำเนินการ...",text="กรุณารอสักครู่"){apiBusy++;if(apiBusy===1&&window.Swal)Swal.fire({title,text,allowOutsideClick:false,allowEscapeKey:false,showConfirmButton:false,didOpen:()=>Swal.showLoading()})}
function loadingClose(){apiBusy=Math.max(0,apiBusy-1);if(apiBusy===0&&window.Swal&&Swal.isVisible())Swal.close()}
async function api(action,p={},auth=true){const body={action,...p};if(auth&&state.session?.token)body.token=state.session.token;loading("กำลังเชื่อมต่อระบบ...","ระบบกำลังดำเนินการ กรุณารอสักครู่");try{const r=await fetch(APP_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify(body)}),t=await r.text();let j;try{j=JSON.parse(t)}catch(e){throw Error("API ส่งข้อมูลกลับมาไม่ใช่ JSON")}if(!j.ok){if(j.error==="SESSION_EXPIRED")forceLogout();throw Error(j.error||"เกิดข้อผิดพลาด")}return j}finally{loadingClose()}}
async function login(e){e.preventDefault();$("loginBtn").disabled=true;try{const r=await api("login",{username:$("username").value.trim(),password:$("password").value},false);state.session={token:r.data.token,user:r.data.user};state.user=r.data.user;localStorage.setItem(APP_CONFIG.SESSION_KEY,JSON.stringify(state.session));showApp();toast("เข้าสู่ระบบสำเร็จ","success");dashboard()}catch(e){toast(e.message,"error")}finally{$("loginBtn").disabled=false}}
async function logout(){try{await api("logout")}catch(e){}forceLogout("ออกจากระบบแล้ว")}
function forceLogout(m=""){localStorage.removeItem(APP_CONFIG.SESSION_KEY);state.session=null;state.user=null;showLogin();if(m)toast(m)}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userName").textContent=state.user?.FullName||"-";$("userPosition").textContent=state.user?.Position||"-";$("userRoles").textContent=roles().join(" · ");$("newIncomingBtn").classList.toggle("hidden",!isAnyRole(["ADMIN","REGISTRAR"]));$("assistantPanel").classList.toggle("hidden",!hasRole("ASSISTANT_SSO"));$("ssoPanel").classList.toggle("hidden",!hasRole("SSO"));$("staffPanel").classList.toggle("hidden",!hasRole("STAFF"))}
async function dashboard(){try{const r=await api("getDashboard"),d=r.data||{},c=d.counts||{};$("totalDocs").textContent=d.total||0;$("countAssistant").textContent=c.WAIT_ASSISTANT_OPINION||0;$("countSSO").textContent=c.WAIT_SSO||0;$("countAck").textContent=c.WAIT_ACKNOWLEDGEMENT||0;$("countProgress").textContent=c.IN_PROGRESS||0;$("countCompleted").textContent=c.COMPLETED||0;await loadDocs();if(hasRole("ASSISTANT_SSO"))await loadAssistantQueue();if(hasRole("SSO"))await loadSSOQueue();if(hasRole("STAFF"))await loadStaffQueue()}catch(e){toast(e.message,"error")}}
async function loadAssistantQueue(){try{const docs=(await api("getDocuments",{status:"WAIT_ASSISTANT_OPINION",documentType:"INCOMING"})).data||[];$("assistantRows").innerHTML=docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||"-")}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(formatThaiDate(d.ReceiveDate))}</td><td class="px-4 py-3 text-right"><button class="px-3 py-1.5 rounded-lg bg-slate-800 text-white" onclick="openOpinion('${jse(d.DocumentID)}')">ให้ความเห็น</button></td></tr>`).join("");$("assistantEmpty").classList.toggle("hidden",!!docs.length);$("assistantCount").textContent=docs.length}catch(e){toast(e.message,"error")}}
async function loadSSOQueue(){try{const docs=(await api("getDocuments",{status:"WAIT_SSO",documentType:"INCOMING"})).data||[];$("ssoRows").innerHTML=docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||"-")}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(formatThaiDate(d.ReceiveDate))}</td><td class="px-4 py-3 text-right"><button class="px-3 py-1.5 rounded-lg bg-slate-800 text-white" onclick="openSSOReview('${jse(d.DocumentID)}')">พิจารณา/มอบหมาย</button></td></tr>`).join("");$("ssoEmpty").classList.toggle("hidden",!!docs.length);$("ssoCount").textContent=docs.length}catch(e){toast(e.message,"error")}}
async function loadStaffQueue(){try{const docs=(await api("getDocuments",{status:"WAIT_ACKNOWLEDGEMENT",documentType:"INCOMING"})).data||[];$("staffRows").innerHTML=docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||"-")}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(status(d.CurrentStatus))}</td><td class="px-4 py-3 text-right"><button class="px-3 py-1.5 rounded-lg bg-slate-800 text-white" onclick="openTask('${jse(d.DocumentID)}')">เปิดงาน</button></td></tr>`).join("");$("staffEmpty").classList.toggle("hidden",!!docs.length);$("staffCount").textContent=docs.length}catch(e){toast(e.message,"error")}}
async function openOpinion(id){try{const d=(await api("getDocument",{documentId:id})).data||{},x=d.document||{};$("opinionDocumentId").value=x.DocumentID||id;$("opinionRegisterNo").textContent=x.RegisterNo||"-";$("opinionSubject").textContent=x.Subject||"-";$("opinionSender").textContent=x.SenderOrganization||x.SenderName||"-";$("suggestedUser").innerHTML='<option value="">-- เลือกผู้รับผิดชอบ --</option>';const users=(await api("getAssignableUsers")).data||[];users.forEach(u=>{const o=document.createElement("option");o.value=u.UserID;o.textContent=`${u.FullName} — ${u.Position||""}`;$("suggestedUser").appendChild(o)});$("opinionText").value="";$("opinionModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function closeOpinion(){$("opinionModal").classList.add("hidden")}
async function saveOpinion(e){e.preventDefault();const id=$("opinionDocumentId").value,suggested=$("suggestedUser").value;if(!suggested)return toast("กรุณาเลือกผู้รับผิดชอบที่เสนอ","error");const b=$("saveOpinionBtn");b.disabled=true;try{await api("submitOpinion",{documentId:id,data:{OpinionType:"RECOMMEND_ASSIGN",SuggestedUserID:suggested,OpinionText:$("opinionText").value.trim()}});closeOpinion();toast("บันทึกความเห็นและส่งต่อให้ สสอ. แล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function openSSOReview(id){try{const d=(await api("getDocument",{documentId:id})).data||{},x=d.document||{},opinions=d.opinions||[],last=opinions.length?opinions[opinions.length-1]:null;$("assignDocumentId").value=x.DocumentID||id;$("assignRegisterNo").textContent=x.RegisterNo||"-";$("assignSubject").textContent=x.Subject||"-";$("assignAssistantOpinion").textContent=last?.OpinionText||"ไม่มีข้อความเพิ่มเติม";$("assignSuggestedUser").textContent=last?.SuggestedUserID?`ผู้รับผิดชอบที่ ผช.สสอ. เสนอ: ${last.SuggestedUserID}`:"ไม่ได้ระบุผู้รับผิดชอบที่เสนอ";$("assignedTo").innerHTML='<option value="">-- เลือกผู้รับผิดชอบ --</option>';const users=(await api("getAssignableUsers")).data||[];users.forEach(u=>{const o=document.createElement("option");o.value=u.UserID;o.textContent=`${u.FullName} — ${u.Position||""}`;$("assignedTo").appendChild(o)});if(last?.SuggestedUserID&&users.some(u=>u.UserID===last.SuggestedUserID))$("assignedTo").value=last.SuggestedUserID;$("commandText").value="เห็นควรดำเนินการตามรายละเอียดข้างต้น";$("additionalText").value="";$("assignModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function closeAssign(){$("assignModal").classList.add("hidden")}
async function saveAssignment(e){e.preventDefault();const id=$("assignDocumentId").value,assignedTo=$("assignedTo").value;if(!assignedTo)return toast("กรุณาเลือกผู้รับมอบหมาย","error");if(!$("commandText").value.trim())return toast("กรุณาระบุคำสั่ง/ข้อความมอบหมาย","error");const b=$("saveAssignBtn");b.disabled=true;try{await api("assignDocument",{documentId:id,assignedTo,data:{CommandText:$("commandText").value.trim(),AdditionalText:$("additionalText").value.trim()}});closeAssign();toast("มอบหมายงานสำเร็จ และส่งให้ผู้รับมอบหมายแล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function openTask(id){try{const d=(await api("getDocument",{documentId:id})).data||{},x=d.document||{},a=(d.assignments||[]).slice(-1)[0]||null;state.currentTask={document:x,assignment:a};$("taskDocumentId").value=x.DocumentID||id;$("taskRegisterNo").textContent=x.RegisterNo||"-";$("taskStatus").textContent=status(x.CurrentStatus);$("taskSubject").textContent=x.Subject||"-";$("taskCommand").textContent=a?.CommandText||"-";$("taskAdditional").textContent=a?.AdditionalText?`เพิ่มเติม: ${a.AdditionalText}`:"";const waiting=x.CurrentStatus==="WAIT_ACKNOWLEDGEMENT";$("ackSection").classList.toggle("hidden",!waiting);$("progressSection").classList.toggle("hidden",waiting);$("ackTaskBtn").classList.toggle("hidden",!waiting);$("progressTaskBtn").classList.toggle("hidden",waiting);$("completeTaskBtn").classList.toggle("hidden",waiting);$("ackText").value="";$("taskNote").value="";$("taskModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function closeTask(){$("taskModal").classList.add("hidden");state.currentTask=null}
async function acknowledgeTask(){const id=$("taskDocumentId").value,b=$("ackTaskBtn");b.disabled=true;try{await api("acknowledgeDocument",{documentId:id,data:{AckStatus:$("ackStatus").value,AckText:$("ackText").value.trim()}});closeTask();toast("บันทึกการรับทราบ/ปฏิบัติแล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function updateTaskProgress(){const id=$("taskDocumentId").value,b=$("progressTaskBtn");b.disabled=true;try{await api("updateTask",{documentId:id,data:{status:"IN_PROGRESS",note:$("taskNote").value.trim()}});closeTask();toast("บันทึกความคืบหน้าแล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function completeTask(){const id=$("taskDocumentId").value,b=$("completeTaskBtn");b.disabled=true;try{await api("updateTask",{documentId:id,data:{status:"COMPLETED",note:$("taskNote").value.trim()}});closeTask();toast("บันทึกว่าเอกสารดำเนินการเสร็จสิ้นแล้ว","success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function loadDocs(){try{state.docs=(await api("getDocuments",{q:$("documentSearch").value.trim(),status:$("statusFilter").value,documentType:$("typeFilter").value})).data||[];renderDocs()}catch(e){toast(e.message,"error")}}
function renderDocs(){$("documentRows").innerHTML=state.docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||d.DocumentNo||"-")}</td><td class="px-4 py-3">${esc(type(d.DocumentType))}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(formatThaiDate(d.ReceiveDate||d.BookDate))}</td><td class="px-4 py-3">${badge(d.CurrentStatus)}</td><td class="px-4 py-3 text-right"><button class="text-blue-700" onclick="openDoc('${jse(d.DocumentID)}')">ดูรายละเอียด</button></td></tr>`).join("");$("emptyDocuments").classList.toggle("hidden",!!state.docs.length)}
async function openDoc(id){try{const d=(await api("getDocument",{documentId:id})).data||{},x=d.document||{};state.currentDocument=d;$("modalTitle").textContent=x.Subject||"รายละเอียดเอกสาร";$("modalSubTitle").textContent=`${type(x.DocumentType)} · ${x.RegisterNo||x.DocumentNo||"-"}`;$("documentDetail").innerHTML=`<div class="grid md:grid-cols-2 gap-4">${item("ประเภท",type(x.DocumentType))}${item("เลขทะเบียน/เลขที่",x.RegisterNo||x.DocumentNo||"-")}${item("วันที่รับ",formatThaiDate(x.ReceiveDate))}${item("เวลารับ",formatThaiTime(x.ReceiveTime))}${item("วันเวลารับ",formatThaiDateTime(x.ReceiveDate,x.ReceiveTime))}${item("ผู้ส่ง",x.SenderName||"-")}${item("หน่วยงานผู้ส่ง",x.SenderOrganization||"-")}${item("เรื่อง",x.Subject||"-")}${item("สถานะ",status(x.CurrentStatus))}${item("ความเร่งด่วน",x.UrgencyLevel||"-")}${item("กำหนดดำเนินการ",formatThaiDate(x.DueDate))}</div>`;renderOpinions(d.opinions||[]);$("fileList").innerHTML=(d.files||[]).map(f=>`<div class="border rounded-xl p-3 flex justify-between items-center gap-3"><span>${esc(f.FileName)}</span><a target="_blank" rel="noopener" class="text-blue-700" href="https://drive.google.com/file/d/${encodeURIComponent(f.DriveFileID)}/view">เปิดไฟล์</a></div>`).join("")||"ยังไม่มีไฟล์";$("workflowTimeline").innerHTML=(d.workflow||[]).map(w=>`<div class="border-l-2 border-slate-300 pl-4 pb-4"><b>${esc(workflowLabel(w.ActionCode))}</b><div class="text-xs text-slate-500">${esc(formatThaiDateTimeFromDateTime(w.ActionDateTime))}</div><div class="text-sm mt-1">${esc(w.Detail||"")}</div></div>`).join("")||"ยังไม่มีประวัติ";renderDocumentActions(x);$("documentModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function renderOpinions(a){const b=$("documentOpinionSection");if(!a.length){b.classList.add("hidden");b.innerHTML="";return}const x=a[a.length-1];b.classList.remove("hidden");b.innerHTML=`<div class="border rounded-xl p-4 bg-slate-50"><div class="font-semibold">ความเห็น ผช.สสอ.</div><div class="text-sm mt-2 whitespace-pre-wrap">${esc(x.OpinionText||"ไม่มีข้อความเพิ่มเติม")}</div><div class="text-xs text-slate-500 mt-2">${esc(formatThaiDate(x.ActionDate))} เวลา ${esc(formatThaiTime(x.ActionTime))}</div></div>`}
function renderDocumentActions(x){const b=$("documentActionBar");b.innerHTML="";if(hasRole("SSO")&&x.CurrentStatus==="WAIT_SSO"){const q=document.createElement("button");q.className="px-5 py-2.5 rounded-xl bg-slate-800 text-white";q.textContent="พิจารณาและมอบหมาย";q.onclick=()=>{$("documentModal").classList.add("hidden");openSSOReview(x.DocumentID)};b.appendChild(q)}if(hasRole("STAFF")&&(x.CurrentStatus==="WAIT_ACKNOWLEDGEMENT"||x.CurrentStatus==="IN_PROGRESS")){const q=document.createElement("button");q.className="px-5 py-2.5 rounded-xl bg-slate-800 text-white";q.textContent=x.CurrentStatus==="WAIT_ACKNOWLEDGEMENT"?"รับทราบ/ปฏิบัติ":"อัปเดตงาน";q.onclick=()=>{$("documentModal").classList.add("hidden");openTask(x.DocumentID)};b.appendChild(q)}}
function openIncoming(){$("incomingModal").classList.remove("hidden");const n=new Date();$("receiveDate").value=localDateInput(n);$("receiveTime").value=localTimeInput(n)}function closeIncoming(){$("incomingModal").classList.add("hidden");$("incomingForm").reset()}
async function saveIncoming(e){e.preventDefault();const f=$("mainPdf").files[0];if(!f)return toast("กรุณาเลือก PDF","error");if(f.type!=="application/pdf")return toast("รองรับเฉพาะ PDF","error");if(f.size>10*1024*1024)return toast("ไฟล์เกิน 10 MB","error");const b=$("saveIncomingBtn");b.disabled=true;try{const p={DocumentType:"INCOMING",BookNo:$("bookNo").value.trim(),BookDate:$("bookDate").value,ReceiveDate:$("receiveDate").value,ReceiveTime:$("receiveTime").value,SenderName:$("senderName").value.trim(),SenderOrganization:$("senderOrganization").value.trim(),Subject:$("subject").value.trim(),RelatedOrgUnitID:$("relatedOrgUnitID").value.trim(),RelatedJobID:$("relatedJobID").value.trim(),UrgencyLevel:$("urgencyLevel").value,DueDate:$("dueDate").value};const r=await api("createDocument",{data:p}),documentId=r?.data?.DocumentID;if(!documentId)throw Error("API ไม่ได้ส่ง DocumentID กลับมา");const raw=await b64(f);if(!raw)throw Error("อ่านข้อมูล PDF ไม่สำเร็จ");await api("uploadFile",{documentId,fileName:f.name,mimeType:"application/pdf",base64:raw,fileRole:"MAIN_DOCUMENT"});closeIncoming();toast("บันทึกหนังสือรับสำเร็จ เลขรับ "+(r.data.RegisterNo||"-"),"success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
function b64(f){return new Promise((res,rej)=>{const x=new FileReader();x.onload=()=>res(String(x.result).split(",")[1]);x.onerror=rej;x.readAsDataURL(f)})}
async function changePassword(e){e.preventDefault();const n=$("newPassword").value;if(n.length<6)return toast("รหัสผ่านใหม่ต้องมีอย่างน้อย 6 ตัวอักษร","error");if(n!==$("confirmPassword").value)return toast("ยืนยันรหัสผ่านไม่ตรงกัน","error");try{await api("changePassword",{oldPassword:$("oldPassword").value,newPassword:n});$("passwordModal").classList.add("hidden");$("changePasswordForm").reset();toast("เปลี่ยนรหัสผ่านสำเร็จ","success")}catch(e){toast(e.message,"error")}}
function type(x){return({INCOMING:"หนังสือรับ",OUTGOING:"หนังสือส่งออก",CIRCULAR:"หนังสือเวียน",ORDER:"คำสั่ง"})[x]||x||"-"}function status(x){return({WAIT_ASSISTANT_OPINION:"รอความเห็น ผช.สสอ.",WAIT_SSO:"รอ สสอ. พิจารณา",WAIT_ACKNOWLEDGEMENT:"รอรับทราบ",IN_PROGRESS:"กำลังดำเนินการ",COMPLETED:"เสร็จสิ้น",CANCELLED:"ยกเลิก"})[x]||x||"-"}
function workflowLabel(x){return({CREATE_DOCUMENT:"รับเอกสารเข้าระบบ",UPLOAD_FILE:"แนบไฟล์เอกสาร",SUBMIT_OPINION:"ความเห็น ผช.สสอ.โนนสะอาด",ASSIGN_DOCUMENT:"สสอ. มอบหมายผู้รับผิดชอบ",ACKNOWLEDGE:"ผู้รับมอบหมายรับทราบ/ปฏิบัติ",UPDATE_TASK:"บันทึกความคืบหน้าการดำเนินงาน",COMPLETE_TASK:"ดำเนินการเสร็จสิ้น",UPDATE_DOCUMENT:"แก้ไขข้อมูลทะเบียน",CANCEL_DOCUMENT:"ยกเลิกเอกสาร"})[x]||x||"-"}
function badge(x){return`<span class="inline-flex px-2.5 py-1 rounded-full text-xs bg-slate-100">${esc(status(x))}</span>`}function item(a,b){return`<div><div class="text-xs text-slate-500">${esc(a)}</div><div class="font-medium">${esc(b)}</div></div>`}
const TH_MONTHS=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
function parseDateOnly(v){if(!v)return null;const s=String(v).trim(),m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m){const y=+m[1],mo=+m[2],d=+m[3];if(y<1000)return null;return new Date(y,mo-1,d)}const d=new Date(s);return isNaN(d.getTime())?null:d}
function formatThaiDate(v){const d=parseDateOnly(v);return d?`${d.getDate()} ${TH_MONTHS[d.getMonth()]} ${d.getFullYear()+543}`:"-"}
function parseTimeOnly(v){if(!v)return null;const m=String(v).trim().match(/(?:T|\s)?(\d{1,2}):(\d{2})(?::(\d{2}))?/);if(!m)return null;const h=+m[1],min=+m[2];return h>23||min>59?null:{h,min}}
function formatThaiTime(v){const t=parseTimeOnly(v);return t?`${String(t.h).padStart(2,"0")}.${String(t.min).padStart(2,"0")} น.`:"-"}
function formatThaiDateTime(a,b){const d=formatThaiDate(a);return d==="-"?"-":formatThaiTime(b)==="-"?d:`${d} เวลา ${formatThaiTime(b)}`}
function formatThaiDateTimeFromDateTime(v){if(!v)return"-";const s=String(v).trim(),m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m){const d=formatThaiDate(`${m[1]}-${m[2]}-${m[3]}`),t=parseTimeOnly(s);return t?`${d} เวลา ${formatThaiTime(s)}`:d}const d=new Date(s);return!isNaN(d.getTime())&&d.getFullYear()>1900?`${formatThaiDate(d)} เวลา ${String(d.getHours()).padStart(2,"0")}.${String(d.getMinutes()).padStart(2,"0")} น.`:s}
function localDateInput(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function localTimeInput(d){return`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
function toast(m,t="info"){if(window.Swal)Swal.fire({toast:true,position:"bottom-end",icon:t==="error"?"error":t==="success"?"success":t==="warning"?"warning":"info",title:String(m),showConfirmButton:false,timer:3500,timerProgressBar:true});else{const x=$("toast");x.textContent=String(m);x.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.add("hidden"),3500)}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function jse(v){return String(v??"").replace(/\\/g,"\\\\").replace(/'/g,"\\'")}function debounce(f,d){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>f(...a),d)}}
window.openDoc=openDoc;window.openOpinion=openOpinion;window.openSSOReview=openSSOReview;window.openTask=openTask;

/* ========================= V5 OUTGOING ========================= */
async function loadNumberStatus(){if(!isAnyRole(["STAFF","REGISTRAR","ADMIN"]))return;try{const r=await api("getNumberStatus",{year:new Date().getFullYear()+543});renderNumberStatus(r.data||[])}catch(e){toast(e.message,"error")}}
function renderNumberStatus(rows){const el=$("numberStatus");if(!el)return;const names={OUTGOING:"📘 หนังสือออก",CIRCULAR:"📢 หนังสือเวียน",ORDER:"📜 คำสั่ง",APPROVAL:"💰 อนุมัติเบิกจ่าย"};el.innerHTML=rows.map(x=>`<div class="border rounded-2xl p-4"><div class="font-semibold">${esc(names[x.DocumentType]||x.DocumentType)}</div><div class="grid grid-cols-2 gap-3 mt-3 text-sm"><div><div class="text-xs text-slate-500">เลขล่าสุด</div><b>${esc(x.LatestNumber)}</b></div><div><div class="text-xs text-slate-500">เลขถัดไป</div><b>${esc(x.NextNumber)}</b></div></div></div>`).join("")}
function openOutgoing(type){const m=$("outgoingModal");if(!m)return;$("outgoingType").value=type||"OUTGOING";const names={OUTGOING:"📘 หนังสือออก",CIRCULAR:"📢 หนังสือเวียน",ORDER:"📜 คำสั่ง",APPROVAL:"💰 หนังสืออนุมัติเบิกจ่าย"};$("outgoingModalTitle").textContent=names[type]||"ออกหนังสือราชการ";const n=new Date();$("outgoingDate").value=localDateInput(n);$("outgoingFrom").value=APP_CONFIG.ORGANIZATION;m.classList.remove("hidden");loadNumberStatus()}
function closeOutgoing(){if($("outgoingModal")){$("outgoingModal").classList.add("hidden");$("outgoingForm").reset()}}
async function saveOutgoing(e){e.preventDefault();const typev=$("outgoingType").value;if(typev==="APPROVAL")return toast("หนังสืออนุมัติเบิกจ่ายยังรอรูปแบบเลขที่จากสำนักงาน","warning");const b=$("saveOutgoingBtn");b.disabled=true;try{const date=$("outgoingDate").value;const p={DocumentType:typev,RegisterYear:new Date(date).getFullYear()+543,BookDate:date,SenderName:$("outgoingFrom").value.trim(),SenderOrganization:$("outgoingTo").value.trim(),Subject:$("outgoingSubject").value.trim(),RelatedOrgUnitID:$("outgoingGroup").value.trim(),RelatedJobID:$("outgoingJob").value.trim(),DueDate:$("outgoingDueDate").value,BookNo:$("outgoingBookNo").value.trim(),UrgencyLevel:"ปกติ"};const r=await api("createDocument",{data:p});if(!r?.data?.DocumentID)throw Error("API ไม่ได้ส่ง DocumentID กลับมา");closeOutgoing();toast(`ออกเลข ${r.data.DocumentNo||"สำเร็จ"} เรียบร้อยแล้ว`,"success");dashboard();loadNumberStatus();loadOutgoingTable()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
async function loadOutgoingTable(){const el=$("outgoingRows");if(!el)return;try{const r=await api("getOutgoingDocuments",{documentType:$("outgoingTypeFilter")?.value||"",q:$("outgoingSearch")?.value.trim()||"",year:new Date().getFullYear()+543});const docs=r.data||[];el.innerHTML=docs.map((d,i)=>`<tr class="border-t"><td class="px-3 py-3">${i+1}</td><td class="px-3 py-3 font-medium">${esc(d.DocumentNo||"-")}</td><td class="px-3 py-3">${esc(formatThaiDate(d.BookDate))}</td><td class="px-3 py-3">${esc(d.SenderOrganization||"-")}</td><td class="px-3 py-3">${esc(d.Subject||"-")}</td><td class="px-3 py-3">${esc(d.SenderName||"-")}</td><td class="px-3 py-3">${esc(status(d.CurrentStatus))}</td><td class="px-3 py-3 text-right"><button class="text-blue-700" onclick="openDoc('${jse(d.DocumentID)}')">ดูรายละเอียด</button></td></tr>`).join("")||`<tr><td colspan="8" class="p-8 text-center text-slate-400">ยังไม่มีรายการ</td></tr>`}catch(e){toast(e.message,"error")}}
function initV5(){if($("outgoingForm"))$("outgoingForm").addEventListener("submit",saveOutgoing);if($("cancelOutgoingBtn"))$("cancelOutgoingBtn").onclick=closeOutgoing;if($("outgoingSearch"))$("outgoingSearch").oninput=debounce(loadOutgoingTable,300);if($("outgoingTypeFilter"))$("outgoingTypeFilter").onchange=loadOutgoingTable;loadNumberStatus();loadOutgoingTable()}
const _oldShowApp=showApp;showApp=function(){_oldShowApp();setTimeout(initV5,0)};window.openOutgoing=openOutgoing;window.closeOutgoing=closeOutgoing;window.loadOutgoingTable=loadOutgoingTable;
