const state={session:null,user:null,docs:[]};
document.addEventListener("DOMContentLoaded",()=>{bind();restore()});
const $=id=>document.getElementById(id);
function bind(){
 $("loginForm").addEventListener("submit",login);$("logoutBtn").onclick=logout;$("refreshBtn").onclick=dashboard;
 $("changePasswordBtn").onclick=()=>$("passwordModal").classList.remove("hidden");$("cancelPasswordBtn").onclick=()=>$("passwordModal").classList.add("hidden");
 $("changePasswordForm").addEventListener("submit",changePassword);$("documentSearch").oninput=debounce(loadDocs,300);
 $("statusFilter").onchange=loadDocs;$("typeFilter").onchange=loadDocs;$("newIncomingBtn").onclick=openIncoming;
 $("cancelIncomingBtn").onclick=closeIncoming;$("incomingForm").addEventListener("submit",saveIncoming);
 $("closeDocumentBtn").onclick=()=>$("documentModal").classList.add("hidden");
}
function restore(){try{let s=JSON.parse(localStorage.getItem(APP_CONFIG.SESSION_KEY)||"null");if(!s?.token)return showLogin();state.session=s;state.user=s.user;showApp();dashboard()}catch(e){showLogin()}}
async function api(action,p={},auth=true){let b={action,...p};if(auth&&state.session?.token)b.token=state.session.token;let r=await fetch(APP_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify(b)}),t=await r.text(),j;try{j=JSON.parse(t)}catch(e){throw Error("API ส่งข้อมูลกลับมาไม่ใช่ JSON")}if(!j.ok){if(j.error==="SESSION_EXPIRED")forceLogout();throw Error(j.error||"เกิดข้อผิดพลาด")}return j}
async function login(e){e.preventDefault();$("loginBtn").disabled=true;try{let r=await api("login",{username:$("username").value.trim(),password:$("password").value},false);state.session={token:r.data.token,user:r.data.user};state.user=r.data.user;localStorage.setItem(APP_CONFIG.SESSION_KEY,JSON.stringify(state.session));showApp();toast("เข้าสู่ระบบสำเร็จ","success");dashboard()}catch(e){toast(e.message,"error")}finally{$("loginBtn").disabled=false}}
async function logout(){try{await api("logout")}catch(e){}forceLogout("ออกจากระบบแล้ว")}
function forceLogout(m=""){localStorage.removeItem(APP_CONFIG.SESSION_KEY);state.session=null;state.user=null;showLogin();if(m)toast(m)}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userName").textContent=state.user?.FullName||"-";$("userPosition").textContent=state.user?.Position||"-";$("userRoles").textContent=(state.user?.Roles||[]).join(" · ");let ok=(state.user?.Roles||[]).some(r=>["ADMIN","REGISTRAR"].includes(r));$("newIncomingBtn").classList.toggle("hidden",!ok)}
async function dashboard(){try{let r=await api("getDashboard");let d=r.data||{},c=d.counts||{};$("totalDocs").textContent=d.total||0;$("countAssistant").textContent=c.WAIT_ASSISTANT_OPINION||0;$("countSSO").textContent=c.WAIT_SSO||0;$("countAck").textContent=c.WAIT_ACKNOWLEDGEMENT||0;$("countProgress").textContent=c.IN_PROGRESS||0;$("countCompleted").textContent=c.COMPLETED||0;await loadDocs()}catch(e){toast(e.message,"error")}}
async function loadDocs(){try{let r=await api("getDocuments",{q:$("documentSearch").value.trim(),status:$("statusFilter").value,documentType:$("typeFilter").value});state.docs=r.data||[];renderDocs()}catch(e){toast(e.message,"error")}}
function renderDocs(){$("documentRows").innerHTML=state.docs.map(d=>`<tr><td class="px-4 py-3 font-medium">${esc(d.RegisterNo||d.DocumentNo||"-")}</td><td class="px-4 py-3">${esc(type(d.DocumentType))}</td><td class="px-4 py-3">${esc(d.Subject||"-")}</td><td class="px-4 py-3">${esc(d.ReceiveDate||d.BookDate||"-")}</td><td class="px-4 py-3">${badge(d.CurrentStatus)}</td><td class="px-4 py-3 text-right"><button class="text-blue-700" onclick="openDoc('${jse(d.DocumentID)}')">ดูรายละเอียด</button></td></tr>`).join("");$("emptyDocuments").classList.toggle("hidden",!!state.docs.length)}
async function openDoc(id){try{let r=await api("getDocument",{documentId:id}),d=r.data||{},x=d.document||{};$("modalTitle").textContent=x.Subject||"รายละเอียดเอกสาร";$("documentDetail").innerHTML=`<div class="grid md:grid-cols-2 gap-4">${item("ประเภท",type(x.DocumentType))}${item("เลขทะเบียน/เลขที่",x.RegisterNo||x.DocumentNo||"-")}${item("วันที่รับ",x.ReceiveDate||"-")}${item("เวลา",x.ReceiveTime||"-")}${item("ผู้ส่ง",x.SenderName||"-")}${item("หน่วยงาน",x.SenderOrganization||"-")}${item("เรื่อง",x.Subject||"-")}${item("สถานะ",status(x.CurrentStatus))}</div>`;$("fileList").innerHTML=(d.files||[]).map(f=>`<div class="border rounded-xl p-3 flex justify-between"><span>${esc(f.FileName)}</span><a target="_blank" class="text-blue-700" href="https://drive.google.com/file/d/${encodeURIComponent(f.DriveFileID)}/view">เปิดไฟล์</a></div>`).join("")||"ยังไม่มีไฟล์";$("workflowTimeline").innerHTML=(d.workflow||[]).map(w=>`<div class="border-l-2 pl-4 pb-4"><b>${esc(w.ActionCode)}</b><div class="text-xs text-slate-500">${esc(w.ActionDateTime||"")}</div><div>${esc(w.Detail||"")}</div></div>`).join("")||"ยังไม่มีประวัติ";$("documentModal").classList.remove("hidden")}catch(e){toast(e.message,"error")}}
function openIncoming(){$("incomingModal").classList.remove("hidden");let n=new Date();$("receiveDate").value=n.toISOString().slice(0,10);$("receiveTime").value=n.toTimeString().slice(0,5)}
function closeIncoming(){$("incomingModal").classList.add("hidden");$("incomingForm").reset()}
async function saveIncoming(e){e.preventDefault();let f=$("mainPdf").files[0];if(!f)return toast("กรุณาเลือก PDF","error");if(f.type!=="application/pdf")return toast("รองรับเฉพาะ PDF","error");if(f.size>10*1024*1024)return toast("ไฟล์เกิน 10 MB","error");let b=$("saveIncomingBtn");b.disabled=true;try{let p={documentType:"INCOMING",bookNo:$("bookNo").value.trim(),bookDate:$("bookDate").value,receiveDate:$("receiveDate").value,receiveTime:$("receiveTime").value,senderName:$("senderName").value.trim(),senderOrganization:$("senderOrganization").value.trim(),subject:$("subject").value.trim(),relatedOrgUnitID:$("relatedOrgUnitID").value.trim(),relatedJobID:$("relatedJobID").value.trim(),urgencyLevel:$("urgencyLevel").value,dueDate:$("dueDate").value};let r=await api("createDocument",{data:p}),raw=await b64(f);await api("uploadFile",{documentId:r.data.DocumentID,fileName:f.name,mimeType:"application/pdf",base64:raw,fileRole:"MAIN_DOCUMENT"});closeIncoming();toast("บันทึกหนังสือรับสำเร็จ เลขรับ "+(r.data.RegisterNo||"-"),"success");dashboard()}catch(e){toast(e.message,"error")}finally{b.disabled=false}}
function b64(f){return new Promise((res,rej)=>{let x=new FileReader();x.onload=()=>res(String(x.result).split(",")[1]);x.onerror=rej;x.readAsDataURL(f)})}
async function changePassword(e){e.preventDefault();let n=$("newPassword").value;if(n.length<6)return toast("รหัสผ่านใหม่ต้องมีอย่างน้อย 6 ตัวอักษร","error");if(n!==$("confirmPassword").value)return toast("ยืนยันรหัสผ่านไม่ตรงกัน","error");try{await api("changePassword",{oldPassword:$("oldPassword").value,newPassword:n});$("passwordModal").classList.add("hidden");$("changePasswordForm").reset();toast("เปลี่ยนรหัสผ่านสำเร็จ","success")}catch(e){toast(e.message,"error")}}
function type(x){return({INCOMING:"หนังสือรับ",OUTGOING:"หนังสือส่งออก",CIRCULAR:"หนังสือเวียน",ORDER:"คำสั่ง"})[x]||x||"-"}
function status(x){return({WAIT_ASSISTANT_OPINION:"รอความเห็น ผช.สสอ.",WAIT_SSO:"รอ สสอ. พิจารณา",WAIT_ACKNOWLEDGEMENT:"รอรับทราบ",IN_PROGRESS:"กำลังดำเนินการ",COMPLETED:"เสร็จสิ้น",CANCELLED:"ยกเลิก"})[x]||x||"-"}
function badge(x){return`<span class="inline-flex px-2.5 py-1 rounded-full text-xs bg-slate-100">${esc(status(x))}</span>`}
function item(a,b){return`<div><div class="text-xs text-slate-500">${esc(a)}</div><div class="font-medium">${esc(b)}</div></div>`}
function toast(m,t="info"){let x=$("toast");x.className=`fixed bottom-5 right-5 z-[100] px-4 py-3 rounded-xl text-white ${t==="error"?"bg-red-600":t==="success"?"bg-emerald-600":"bg-slate-800"}`;x.textContent=m;x.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.add("hidden"),3500)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function jse(v){return String(v??"").replace(/\\/g,"\\\\").replace(/'/g,"\\'")}function debounce(f,d){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>f(...a),d)}}window.openDoc=openDoc;
